make a ucloud-exporter
douban/ucloud-exporter pull request #1
Opened 2022-08-09 09:40 UTC by NightWindD

2022-08-09 09:50 UTC, LeoQuote requested changes
代码重复比较多, 看有无办法复用

2022-08-09 09:50 UTC, LeoQuote commented on main.go
> +	*infoCount = 3
这里为什么要单独赋值

2022-08-09 09:50 UTC, LeoQuote commented on exporter/ucloudexporter.go
> +	"test1/collector"
这个 test1 是干什么的? 能否更有意义一点

2022-08-09 09:50 UTC, LeoQuote commented on main.go
> +		case "acs_cdn":
acs_cdn 是什么, 对于此 exporter 是否是必要的?

2022-08-09 09:50 UTC, LeoQuote commented on main.go
> +	cfg.BaseUrl = "https://api.ucloud.cn"
定义一个常量吧

2022-08-09 09:50 UTC, LeoQuote commented on exporter/ucloudexporter.go
> +	}
这些逻辑和下面的逻辑有些重复, 能否想办法复用?

2022-08-09 09:50 UTC, LeoQuote commented on exporter/ucloudexporter.go
> +	}
为什么需要多次for 循环, 能否统一到一个循环?

2022-08-09 09:50 UTC, LeoQuote commented on go.mod
> +module test1
test1 能否改为更有意义的名字?

2022-08-09 10:31 UTC, LeoQuote commented on collector/collector.go
> +		log.Println(err)
这里直接报错吧, 不要这样沉默的失败了

2022-08-09 10:32 UTC, LeoQuote commented on collector/collector.go
> +		log.Println(err)
如果到这里, 让程序退出, 或者http 返回错误

2022-08-09 10:40 UTC, LeoQuote commented on exporter/ucloudexporter.go
> +		)
这里逻辑就我看来会导致里面所有的 域名平均值指标一样, 你这样写是什么考虑呢?

2022-08-09 10:47 UTC, LeoQuote commented on exporter/ucloudexporter.go
> +	infoList             [20]*string
这里的 infoCount 能否由 infoList 取得? infoCount 是不是一个多余的变量?

2022-08-09 12:59 UTC, NightWindD commented on exporter/ucloudexporter.go
> +		)
这个地方目前只有一个域名，如果要做多个域名循环的话还要额外请求域名id，在计算平均值时把各个域名的平均值算出来做成average的数组在这里变成requestHitRateAverage[i]就可以了，对于只有一个域名的时候多了请求会有点浪费我就这么写了

2022-08-09 14:57 UTC, NightWindD commented on exporter/ucloudexporter.go
> +	infoList             [20]*string
这个我又尝试了一下 还是觉得这样那infocount做循环比较好 如果定义infoList[20]*string 没有被填入域名的地方是nil 也会被len计算 所以还是用一下count比较好

2022-08-09 15:11 UTC, LeoQuote commented on exporter/ucloudexporter.go
> +	infoList             [20]*string
那么，golang里面有没有一种数据类型，具有不定长的特性，满足你的需求呢？你有没有进行相关的探索呢？

2022-08-09 15:13 UTC, LeoQuote commented on exporter/ucloudexporter.go
> +		)
写代码首先要去考虑正确性，你这个逻辑能保证正确性吗？如何保证？

2022-08-11 00:56 UTC, LeoQuote commented on exporter/ucloudexporter.go
> +		httpList := collector.RetrieveOriginHttpCode4xx(domain.DomainId, e.projectId, e.rangeTime, e.delayTime, e.client).HttpCodeDetail
这一部分的命名可以更贴切一点吗？httpData 会不会更好，下面的httpData 更名为 httpSum 是不是会更好？其他的变量也是类似的

2022-08-11 08:56 UTC, LeoQuote commented on collector/collector.go
> +		panic(err)
这里也 log.Fatal 吧

2022-08-11 09:09 UTC, NightWindD commented on collector/collector.go
> +		panic(err)
这个最新一版里应该已经log.fatal了

2022-08-12 04:08 UTC, LeoQuote requested changes
如果域名列表为空, 可以直接报错退出

2022-08-12 05:39 UTC, merged